db.articles.insertMany([
  {
    _id: new ObjectId(),
    titre: "Introduction à MongoDB",
    contenu: "MongoDB est une base de données NoSQL.",
    auteur: "John Doe",
    date_creation: new Date(),
    tags: ["MongoDB", "NoSQL"],
  },
  {
    _id: new ObjectId(),
    titre: "Les bases de MongoDB",
    contenu: "Apprenez les commandes de base pour utiliser MongoDB.",
    auteur: "Jane Smith",
    date_creation: new Date(),
    tags: ["MongoDB", "Tutoriel"],
  },
  {
    _id: new ObjectId(),
    titre: "Avantages des bases de données NoSQL",
    contenu: "Découvrez pourquoi choisir une base de données NoSQL.",
    auteur: "Alex Brown",
    date_creation: new Date(),
    tags: ["NoSQL", "Database"],
  },
  {
    _id: new ObjectId(),
    titre: "Installation de MongoDB",
    contenu: "Guide étape par étape pour installer MongoDB.",
    auteur: "Emily White",
    date_creation: new Date(),
    tags: ["MongoDB", "Installation"],
  },
  {
    _id: new ObjectId(),
    titre: "Requêtes avancées dans MongoDB",
    contenu: "Apprenez à utiliser des requêtes complexes avec MongoDB.",
    auteur: "Michael Green",
    date_creation: new Date(),
    tags: ["MongoDB", "Requêtes", "Avancé"],
  },
  {
    _id: new ObjectId(),
    titre: "Meilleures pratiques pour MongoDB",
    contenu: "Des conseils pour optimiser votre utilisation de MongoDB.",
    auteur: "Laura Black",
    date_creation: new Date(),
    tags: ["MongoDB", "Pratiques", "Optimisation"],
  },
]);
